## TASK 1

#### Q.1 Write a function to compute 5/0 and use try/except to catch the exceptions.

In [1]:
5/0

ZeroDivisionError: division by zero

In [2]:
a=5
b=0
try:
    print(a/b)
    
except Exception as e:
    print("Something went wrong!!")
    
finally:
    print("Code Executed")

Something went wrong!!
Code Executed


In [3]:
a=5
b=0
try:
    print(a/b)

# if we specify the exact error name then the code will hit that particular exception.
except ZeroDivisionError as e:
    print("Denominator should never be zero while division..")
    
except Exception as e:
    print("Something went wrong!!")
    
finally:
    print("Code Executed")

Denominator should never be zero while division..
Code Executed


#### Q.2 Implement a Python program to generate all sentences where subject is in ["Americans", "Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"]. 

### Hint: Subject,Verb and Object should be declared in the program as shown below.
##### subjects=["Americans ","Indians"]
##### verbs=["play","watch"]
##### objects=["Baseball","Cricket"]

### Output should come as below:
##### Americans play Baseball.
##### Americans play Cricket.
##### Americans watch Baseball.
##### Americans watch Cricket.
##### Indians play Baseball.
##### Indians play Cricket.
##### Indians watch Baseball.
##### Indians watch Cricket.

In [4]:
subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]

sentence=[(i + " " + j + " " + k) for i in subjects for j in verbs for k in objects]
print(sentence)
print()
for t in sentence:
 print (t)

['Americans  play Baseball', 'Americans  play Cricket', 'Americans  watch Baseball', 'Americans  watch Cricket', 'Indians play Baseball', 'Indians play Cricket', 'Indians watch Baseball', 'Indians watch Cricket']

Americans  play Baseball
Americans  play Cricket
Americans  watch Baseball
Americans  watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


## TASK 2

#### Q.1 Write a function so that the columns of the output matrix are powers of the input vector. The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.
HINT: Such a matrix with a geometric progression in each row is named for Alexandre-Theophile Vandermonde.

In [5]:
import numpy as np

x = np.array([1, 2, 3, 5])
N=5
def vander_function(x,N):
    print("Output Matrix: ")
    print(np.column_stack([x**(N-1-i) for i in range(N)]))
    
vander_function(x,N)


Output Matrix: 
[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [625 125  25   5   1]]
